package realisering;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author oskar
 */
public class Login extends javax.swing.JFrame {

    private InfDB mib;

    /**
     * Konstruktor
     */
    public Login(InfDB mib) {
        this.mib = mib;
        initComponents();
    }

    private void loggaIn() {
        Boolean koll = false;
        Boolean isAgent = false;
        String hittaAlien = "SELECT LOSENORD FROM ALIEN;";
        String hittaAgent = "SELECT LOSENORD FROM AGENT;";

        ArrayList<String> allaLosen;
        ArrayList<String> allaLosenAlien;

        try {

            // Sparar lösenord i Arraylist.
            allaLosen = mib.fetchColumn(hittaAgent);
            allaLosenAlien = mib.fetchColumn(hittaAlien);

            // Kollar igenom alla Agenters lösenord
            for (String l : allaLosen) {
                if (l.equals(new String(losenord.getPassword()))) {
                    dispose();
                    System.out.println("Agent");
                    koll = true;
                    isAgent = true;
                    // If-sats som kollar om admin, öppna fönster.
                }
            }

            // Kolalr igenom alla Aliens lösenord.
            for (String l : allaLosenAlien) {
                if (l.equals(new String(losenord.getPassword()))) {
                    dispose();
                    System.out.println("Alien");
                    koll = true;
                    // Öppna fönster för Alien
                }
            }

            // Om lösenordet inte fanns - Meddelande om fel lösenord.
            if (!koll) {
                JOptionPane.showMessageDialog(null, "Fel lösenord!");
            }

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Databasfel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        } catch (Exception ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ettUndantag.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        losenord = new javax.swing.JPasswordField();
        knapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(47, 59, 94));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(400, 315));
        setMinimumSize(new java.awt.Dimension(400, 315));
        setPreferredSize(new java.awt.Dimension(400, 315));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 315));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realisering/Men_In_Black_logo.png"))); // NOI18N

        losenord.setColumns(12);
        losenord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        losenord.setText("123456789123456789");
        losenord.setToolTipText("Ange lösenord");
        losenord.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        losenord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                losenordKeyPressed(evt);
            }
        });

        knapp.setFont(new java.awt.Font("Open Sans SemiBold", 1, 16)); // NOI18N
        knapp.setText("LOGGA IN");
        knapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(knapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(losenord))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(losenord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(knapp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Logga in genom att klicka på knappen
    private void knappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knappActionPerformed
        loggaIn();
    }//GEN-LAST:event_knappActionPerformed
    private void losenordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_losenordKeyPressed
        if (evt.getKeyCode() == 10) {
            loggaIn(); // Logga in genom att trycka enter
        }
    }//GEN-LAST:event_losenordKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton knapp;
    private javax.swing.JPasswordField losenord;
    // End of variables declaration//GEN-END:variables
}
