SELECT * from AGENT;
SELECT * from ALIEN;
SELECT * from BOGLODITE;
SELECT * from FALTAGENT;
SELECT * from FORDON;
SELECT * from INNEHAR_FORDON;
SELECT * from INNEHAR_UTRUSTNING;
SELECT * from KOMMUNIKATION;
SELECT * from OMRADE;
SELECT * from OMRADESCHEF;
SELECT * from PLATS;
SELECT * from SQUID;
SELECT * from TEKNIK;
SELECT * from UTRUSTNING;
SELECT * from VAPEN;
SELECT * from WORM;
SELECT LOSENORD FROM AGENT JOIN ALIEN;

